theme: jekyll-theme-dinky
title: GitHub Collaborative Documentation
description: This tutorial is for new GitHub users to understand main features and how to use them for developing documents collaboratively
